name: xaj-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ipykernel
  - numpy
  - pandas
  - scikit-learn
  - deap
  - spotpy
  - seaborn
  - tqdm
  - sphinx
  - pytest
  - black
  - pip
  - pip:
    - hydrodataset
