on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

name: Linux build
jobs:
    py-check:
        runs-on: ${{ matrix.config.os }}
        name: ${{ matrix.config.os }} (${{ matrix.config.py }})
        strategy:
            fail-fast: false
            matrix:
                config:
                    - { os: ubuntu-latest, py: "3.10" }
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.config.py }}
            - name: Install GDAL
              run: |
                  python -m pip install --upgrade pip
                  pip install --no-cache-dir Cython
                  pip install --find-links=https://girder.github.io/large_image_wheels --no-cache GDAL
            - name: Test GDAL installation
              run: |
                  python -c "from osgeo import gdal"
                  gdalinfo --version
            - name: Install dependencies
              run: |
                  pip install --user -r requirements.txt
                  pip install --user -r requirements_dev.txt
                  pip install .
            - name: Create hydro_setting.yml
              run: |
                  echo 'local_data_path:' > hydro_setting.yml
                  echo '  datasets-origin: /home/runner/.cache/' >> hydro_setting.yml
                  sudo cp hydro_setting.yml /home/runner/hydro_setting.yml
                # Add other settings here as required
            - name: PKG-TEST
              run: |
                  python -m pytest test/test_data_preprocess.py
                #   python -m pytest test/test_xaj.py
                #   python -m pytest test/test_gr4j.py
                #   python -m pytest test/test_hymod.py

